# baseSite: https://www.lds.org/media-library/video/categories?lang=eng&start=1&end=15
baseSite: https://www.lds.org/media-library/video/categories?lang=eng

redisPort: 32768
redisHost: 78.48.1.15

logLevel: info

priority:
  - 720p
  - 360p
  - 1080p